### ISSUE TITLE
OPENAI_API_KEY error

### ISSUE THREAD

**Issue by Burbenpho** [BaderTim/telegram-audio-bot#1]
I create .env with:
--
TELEGRAM_BOT_API_KEY=<*tg_bot_API*>
OPENAI_API_KEY=<sk-*example*>
--
So I use bot.py and then get this error: 
File "/content/telegram-audio-bot/telegram-audio-bot/telegram-audio-bot/telegram-audio-bot/bot.py", line 17, in <module>
    client = OpenAI(
  File "/usr/local/lib/python3.10/dist-packages/openai/_client.py", line 98, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable.
I used colab to run this code, so is it colab problem?

**Comment by BaderTim** [comment]
Hi @Burbenpho, it seems like ```os.environ.get("OPENAI_API_KEY")``` returns ```None``` in your case. This means that dotenv is not able to find your .env file, or it is not defined properly.   
So, yes, it seems to be an issue with how you use Google Colab. I would recommend you to verify that the .env file is in the same folder as bot.py or else just replace ```os.environ.get("OPENAI_API_KEY")``` with your API key directly (only do this if you use a private notebook).
